pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["advanced.htm","Advanced","Advanced Do not show wizard on startup Stop the wizard from being displayed when Zoom is started. Beep at the end of indexing Play the system aler...",""],
["advanced_template_options.htm","Advanced template options","Advanced template options Zoom now provides advanced template options so you can customize the appearance of your search results outside of what i...",""],
["alternative_page_titles_and_de.htm","Alternative page titles and descriptions","Alternative page titles and descriptions In some cases, you may have designed titles and meta descriptions which target Internet-wide search engin...",""],
["authentication.htm","Authentication","Authentication This tab allows you to enter login and password details to spider a secure site that requires authentication. There are two common ...",""],
["autocomplete.htm","Autocomplete","Autocomplete When this feature is enabled, as users type in the search box, a list of suggestions will appear immediately to complete their search...",""],
["base_url.htm","Base URL","Base URL This is the URL where your website will be published and uploaded to. For example, if your website will be published at http://www.myisp....",""],
["base_url_for_cd_rom.htm","Base URL for CD-ROM distribution (absolute and relative paths)","Base URL for CD-ROM distribution (absolute and relative paths) Understanding absolute and relative paths are important to determine the most consi...",""],
["broken_link_detection.htm","Broken link detection","Broken link detection When indexing your website with Zoom (using \" Spider Mode \"), it can also act as an effective broken link detector. Zoom&#39;s s...",""],
["categories.htm","Categories","Categories This allows you to specify categories in your search engine, allowing your users to select from a drop-down to restrict searches to cer...",""],
["cd_rom_distribution.htm","CD-ROM distribution","CD-ROM distribution If you are putting your search engine on a CD-ROM or DVD (Javascript platform only), you should copy the Required Files listed...",""],
["changing_your_default_editor.htm","Changing your default editor","Changing your default editor When you edit a HTML or script file from Zoom (from either the Templates menu or the Configuration Window), it will o...",""],
["client_side_search_engine.htm","Client-side search engine (Using JavaScript)","Client-side search engine (Using Javascript) When to use When you intend to distribute the search engine on a CD-ROM or DVD, or any local Intranet...",""],
["command_line_parameters.htm","Command line parameters","Command line parameters The Zoom Indexer accepts command line parameters if you wish to use it with an automated scheduling program or just to cre...",""],
["configuration_zcfg_files.htm","Configuration (ZCFG) files","Configuration (ZCFG) files The settings of the indexer, including the starting directory, URL, output directory, and configuration settings can be...",""],
["configuring_a_plugin.htm","Configuring a plugin","Configuring a plugin You can configure the behaviour of a plugin by double-clicking on the file extension (or selecting the extension and clicking...",""],
["configuring_zoom.htm","Configuring Zoom further","Configuring Zoom further You can change everything from the indexing behaviour of the search engine, to the appearance and features of the search ...",""],
["config_categories.htm","Categories","Categories Clicking on this tab will bring up the Categories manager. See the following \" Categories \" section for more information. ",""],
["config_custom_meta_search_fields.htm","Custom Meta Search Fields","Custom Meta Search Fields Clicking on this tab will bring up the Custom Meta Fields manager. See the following \" Custom Meta Search Fields \" secti...",""],
["config_ftp.htm","FTP","FTP Clicking on this tab will bring up your settings for uploading files to your web server via FTP. See the dedicated \" FTP \" section for more in...",""],
["contacting_us.htm","Contacting us","Contacting us Web: http://www.wrensoft.com/zoom/ E-mail: zoom@wrensoft.com Visit our website for more contact information. ",""],
["content_filtering.htm","Content filtering","Content filtering Content Filtering allows you to filter out an entire page based on words found within the page&#39;s content. A list of filter words...",""],
["credits.htm","Credits","Credits Zoom Search Engine&#8482; is developed by Wrensoft&#174; Web Development, a subsidiary of PassMark&#8482; Software. All scripts, binaries, and documentatio...",""],
["css_class_listing.htm","CSS class listing","CSS class listing Style class Description .highlight The appearance of the highlighted search words in the results, when highlighting is enabled. ...",""],
["customizing_icons_and_thumbs.htm","Customizing the appearance of your icons or thumbnails","Customizing the appearance of your icons or thumbnails The size and appearance of your icon or thumbnail images are defined by CSS just as the res...",""],
["customizing_the_recommended_li.htm","Customizing the recommended links","Customizing the recommended links The following are the class names used to define the style and appearance of the search results. You can specify...",""],
["customizing_the_search_form.htm","Customizing the search form","Customizing the search form The following are the class names used to define the style and appearance of the search form. (Note: that this only ap...",""],
["customizing_the_search_results.htm","Customizing the search results","Customizing the search results The following are the class names used to define the style and appearance of the search results. There are some com...",""],
["custom_meta_search_fields.htm","Custom Meta Search Fields","Custom Meta Search Fields You can specify custom meta fields that you want Zoom to index and make searchable. This is typically useful for online ...",""],
["date_range_searching.htm","Date Range Searching","Date Range Searching When this option is enabled, the visitor will be able to specify a date range which search results must fall between. The use...",""],
["discussion_forums.htm","Discussion forums","Discussion forums You can visit our online discussion forum for help and advice on using Zoom. It is an active community made up of many Zoom user...",""],
["editing_the_search_script.htm","Editing the search script","Editing the search script If you are familiar with scripting, you can edit the search script source code by clicking on the &#8220;Templates&#8221; menu in th...",""],
["eula.htm","End User License Agreement (EULA)","End User License Agreement (EULA) PassMark&#174; Software Pty Ltd trading as Wrensoft&#8482; (‘Wrensoft’) End User Licence Agreement (‘EULA’) IMPORTANT! PLEA...",""],
["european_languages.htm","European languages (French, German, Danish, Swedish, etc.)","European languages (French, German, Danish, Swedish, etc.) European websites commonly use the &#8220;Western European&#8221; character encoding, CP1252 (also ...",""],
["faqs.htm","Frequently Asked Questions (FAQs)","Frequently Asked Questions (FAQs) We provide an extensive and up-to-date online support section with many Frequently Asked Questions (FAQs) and so...",""],
["features.htm","Features","Features The following is a brief list of the basic features provided by Zoom, Easy to use and user friendly indexer application which runs from y...",""],
["files_required.htm","Files required","Files required The following is a list of files required to install a server-side search engine on your website. They will be created in the Outpu...",""],
["files_required_js.htm","Files required","Files required Note that all files required will be created in the Output Directory at the end of indexing. Filename Purpose Notes search.html Sea...",""],
["file_formats_supported.htm","File formats supported","File formats supported We currently provide plugin support to allow for indexing and searching of the following file formats: Extension File type ...",""],
["ftp.htm","FTP","FTP There is no inbuilt FTP functionality in the Linux version of Zoom as it was designed for the purpose of running it on the web server and as s...",""],
["how_can_i_add_a_search_form.htm","How can I add a search form to my menus, main page, etc.?","How can I add a search form to my menus, main page, etc.? If you want to add a simple search form on your website’s main page, or navigation bar, ...",""],
["how_do_i_customize_the_look.htm","How do I customize the look of my search page?","How do I customize the look of my search page? You can completely alter the appearance of the search page, from changing the fonts and layout to i...",""],
["how_do_i_modify_search_form.htm","How do I modify the search form on the search page?","How do I modify the search form on the search page? If you wish to modify the search form, you can either edit the script, or define your own sear...",""],
["how_to_enter_in_my_license_key.htm","How to enter in my license key","How to enter in my license key After purchasing the software a license key is sent out via E-mail. This license key needs to be entered into the Z...",""],
["how_zoom_works.htm","How Zoom works","How Zoom works Below is an illustrated representation of how Zoom works. As you can see, there are two main components to Zoom: the Zoom Indexer a...",""],
["icons.htm","Associating icon images with a file type","Associating icon images with a file type You can associate an icon image with a certain file type so that whenever these files appear in your sear...",""],
["icons_and_thumbnails.htm","Icons and thumbnails","Icons and thumbnails You can now associate an image with each file or web page in your index. These images will be displayed alongside the links i...",""],
["image_indexing.htm","Image indexing","Image indexing Image files (JPG, GIF, PNG and TIFF) can be searched for and indexed by Zoom using our ImageInfo plugin. Note that plugin support i...",""],
["importing_and_exporting.htm","Importing and Exporting additional start URLs","Importing and Exporting additional start URLs In spider mode, you can import additional spider URLs from a text file by clicking on the Import but...",""],
["incremental_addpages.htm","Add list of new or updated pages","Add list of new or updated pages This feature allows you to specify a list of new pages which are to be indexed and added to the existing index. I...",""],
["incremental_addstartpts.htm","Add start points to existing index","Add start points to existing index This option allows you to add and index a list of start points (usually a new website, or a part of a new websi...",""],
["incremental_commandline.htm","Command-line parameters for incremental indexing","Command-line parameters for incremental indexing We&#39;ve added a list of command-line parameters to Zoom that will allow you to call upon the above ...",""],
["incremental_delete.htm","View or delete pages from existing index","View or delete pages from existing index This option allows you to browse the list of pages which exist in your current index. It also allows you ...",""],
["incremental_indexing.htm","Incremental indexing","Incremental indexing Zoom allows you to perform incremental indexing so that you can update, add pages, and make changes to an existing set of ind...",""],
["incremental_updating.htm","Updating an existing index","Updating an existing index This option will look through the list of pages found in your existing index and check if they have since been modified...",""],
["indexing_options.htm","Indexing options","Indexing options What to index You can specify the parts of a page that should be included or excluded from indexing here. This includes the page ...",""],
["indexing_status.htm","Indexing status","Indexing status The Status tab provides an overview of the indexing process such as the number of words found, the number of links found, and the ...",""],
["index_log.htm","Index log","Index log You can configure the type of messages that are displayed in the main status log window during an indexing session here. This allows you...",""],
["installation_linux.htm","Installation","Installation Prequisites: Apache, PHP5 and the Apache PHP5 module must be installed and working correctly. Access to the files via the command lin...",""],
["installing_a_plugin.htm","Installing a plugin","Installing a plugin Download the plugin required from the Zoom website. To install an individual plugin, unzip the file downloaded to the \"plugins...",""],
["installing_the_asp_net_native_.htm","Installing the ASP.NET native control","Installing the ASP.NET native server control Note that this procedure is not necessary for the PHP, Classic ASP or CGI versions. If you are using ...",""],
["integrating_zoom.htm","Integrating Zoom in your own applications","Integrating Zoom in your own applications Software developers looking to include a search engine feature as part of their own applications can int...",""],
["international__foreign_languag.htm","International / foreign language support","International / foreign language support Zoom supports a wide variety of languages such as French, German, Italian, Hebrew, Cyrillic (Russian), Gr...",""],
["introduction.htm","Introduction","Introduction Zoom Search Engine&#8482; is a package for web developers to easily add a search function to their web site, CD-ROM, DVD or Intranet. It ha...",""],
["japanese.htm","Japanese","Japanese Japanese websites commonly use one of two encodings: Shift-JIS, and Unicode UTF-8. Zoom does not currently support indexing Shift-JIS web...",""],
["jump_to_match_and_highlight.htm","Enable jump to match and highlight within document","Enable jump to match and highlight within document You can setup highlighting to occur on the actual page of your website when you click on a sear...",""],
["known_issues.htm","Known issues","Known issues The following are some known issues, technical limitations and their possible solutions or workarounds. Note that we can provide cust...",""],
["languages.htm","Languages","Languages Zoom provides options to cater to searching sites of different languages and encodings. For additional information, please see &#8220; Interna...",""],
["lastmodifieddate.htm","Specifying a last-modified date for your web pages","Specifying a last-modified date for your web pages You can configure Zoom to display the date and time for each search result and allow the user t...",""],
["limitations_of_javascript.htm","Limitations of Javascript","Limitations of Javascript While Javascript has the advantage of having no server-side requirements, it does have some significant disadvantages du...",""],
["limits.htm","Limits","Limits These are the defined limits of the indexer, setting the maximum number of files to scan, maximum number of unique words to index, maximum ...",""],
["log.htm","Log","Log The \"Log\" tab provides detailed information on the indexing process. You should evaluate these messages to determine what files have been inde...",""],
["more_how_tos.htm","More how-to&#39;s","More how-to&#39;s For more how-to’s regarding customizing your search page and integrating it with your site, visit our Support and FAQ webpage online...",""],
["notes_for_upgrading_from_v3.htm","Notes for users upgrading from Zoom 3.x","Notes for users upgrading from Zoom 3.x Users upgrading their sites and indexing configurations from Zoom 3.x should note some significant differe...",""],
["notes_for_upgrading_from_v4.htm","Notes for users upgrading from Zoom 4.x","Notes for users upgrading from Zoom 4.x Due to the introduction of new CSS classes (and the removal of some old CSS classes), we would recommend t...",""],
["offline_mode.htm","Offline mode","Offline mode Offline mode indexes a local copy of your website, stored on your hard disk. This is effective for static web pages and allows the us...",""],
["other_tips.htm","Other tips","Other tips A small index is a fast index. Filter directories, pages and words that contain redundant or useless information (from a search engine ...",""],
["output_directory.htm","Output directory","Output directory This is the directory in which the index files generated will be saved. Usually you would put this in the same directory as your ...",""],
["output_folder_and_limit_step.htm","Output folder and limit step","Output folder and limit step Zoom will create a set of index files, which will be required for your search function. Specify a folder here for Zoo...",""],
["platform.htm","Platform","Platform This setting selects the script platform, which you will host or distribute your search engine with. Select from either PHP, ASP, ASP.NET...",""],
["plugins.htm","Plugins (Indexing PDF, DOC and other document formats)","Plugins (Indexing PDF, DOC and other document or file formats) Searching and indexing non-HTML (text) files such as Word documents and PDF files r...",""],
["purchasing_zoom.htm","Purchasing Zoom","Purchasing Zoom If you wish to use Zoom for a larger website, or you are using it in a commercial project, require professional support, custom fe...",""],
["recommended_links.htm","Recommended links","Recommended links This feature allows you to specify a list of keywords or phrases that you can associate with specific URLs. When a user does a s...",""],
["results_layout.htm","Results layout","Results layout Search results layout This set of options allows you to modify the appearance of the search results. You can select or disable the ...",""],
["russian_cyrillic.htm","Russian (Cyrillic)","Russian (Cyrillic) Russian websites commonly use one of three encodings: KOI8, CP1251 (aka \"windows-1251\"), and Unicode UTF-8. If your website use...",""],
["scan_options.htm","Scan options","Scan options Scan Extensions This is a list of the filename extensions that will be scanned by the indexer. If a file has an extension that is not...",""],
["scheduling_and_automatic_index.htm","Scheduling and automatic indexing","Scheduling and automatic indexing To setup Zoom to automatically index your site under Linux you can setup a cron job using the \"crontab\" command ...",""],
["search_page.htm","Search page","Search page These are options specific to changing the appearance, or behaviour of the search page from which searches are entered and results are...",""],
["search_statistics_script.htm","Search Statistics PHP Script","Search Statistics PHP Script If you have PHP support on your web server, you can use a provided script (\"report.php\") to provide online reporting ...",""],
["select_file_types.htm","Select file types step","Select file types step Here you can select the file types you wish to include in your search functions. Note that you can specify exact file exten...",""],
["server_side_search_engine.htm","Server-side search engine (Using PHP, ASP, or CGI)","Server-side search engine (Using PHP, ASP, or CGI) When to use When your web server supports PHP or ASP, or has CGI execute permission When you do...",""],
["sitemaps.htm","Sitemaps","Sitemaps This option allows you to generate a plain text sitemap (compatible with Yahoo Sitemaps) and a XML sitemap (compatible with Google Sitema...",""],
["skipping_sections_of_a_page.htm","Skipping sections of a page","Skipping sections of a page Sometimes there are situations where you would want to stop a section of a page from being indexed. This may be common...",""],
["skip_options.htm","Skip options","Skip options Page and folder skip list This is a list of pages and folders that will not be scanned during the indexing process. Note that filenam...",""],
["spider_mode.htm","Spider mode","Spider mode Spider mode indexes a remote copy of your website already uploaded and hosted on a web server. It does this via the use of a ‘spider’,...",""],
["spider_options.htm","Spider options","Spider options Spider downloading options These are options which control the way in which Zoom will download files when it is in spider mode. Not...",""],
["start_directory.htm","Start directory (offline mode only)","Start directory (offline mode only) The start directory specifies the local directory for the offline scanning to begin in. All sub-directories un...",""],
["start_indexing.htm","Start indexing","Start indexing This starts the indexer using the current settings in the mode selected. When the process finishes, &#8220;Indexing completed&#8221; will appea...",""],
["start_spider_url.htm","Start spider URL (spider mode only)","Start spider URL (spider mode only) In spider mode , you are required to specify the URL from which the indexer will start the spider scanning fro...",""],
["step_by_step_wizard.htm","Step-by-step Wizard","Step-by-step Wizard When you start Zoom Indexer for the first time, you will be greeted with a Wizard which can guide you through the basics of se...",""],
["stop_indexing.htm","Stop indexing","Stop indexing This requests the indexing process to stop. Note that the indexer will attempt to finish indexing the file it was up to, and will ge...",""],
["synonyms.htm","Synonyms","Synonyms This feature allows you to specify synonyms, variations of words, common misspellings, etc. and allow you to map them to an equivalent wo...",""],
["system_requirements.htm","System Requirements","System Requirements For indexing your site (using Zoom Indexer) The Zoom Indexer can run on any computer with the following specifications: Linux ...",""],
["technical_limitations.htm","Technical limitations","Technical limitations We document technical limitations of the software because we understand the importance for advanced users or developers to h...",""],
["the_indexing_process.htm","The indexing process","The indexing process For your information, we have documented the basic process in which text is extracted from the HTML source file. This may be ...",""],
["thumbnails.htm","Associating thumbnail images with files","Associating thumbnail images with files You can associate thumbnail images for your files so that a small preview of each file can be displayed al...",""],
["translating_the_search_page.htm","Translating the search page","Translating the search page You can modify the text that appears on the search page by editing the Zoom Language Files (.ZLANG files) from the Con...",""],
["unsupported_binary_formats.htm","Unsupported binary formats","Unsupported binary formats There are some binary file formats which are recognized by Zoom but there is no plugin available to extract content or ...",""],
["upgrading_a_plugin.htm","Upgrading a plugin","Upgrading a plugin As new versions of the plugins become available on the website, simply copy them into the same &#8220;plugins&#8221; directory that they we...",""],
["uploading_cgi.htm","Additional notes for uploading CGI","Additional notes for uploading CGI If you are using the CGI version, note that many web servers are set up to only execute CGI from a certain dire...",""],
["uploading_to_your_website.htm","Uploading to your website","Uploading to your website You will need to upload the files listed under &#8220;Required Files&#8221; to your web server. You can either use Zoom to upload th...",""],
["using_cgi_on_cd.htm","Using the CGI or PHP version without a web server","Using the CGI or PHP version without a web server While Javascript is a good solution for distributing small sites on CD it is limited in what it ...",""],
["using_desc_files.htm","Using custom description (.desc) files","Using custom description (.desc) files As many external binary documents do not contain useful title and description information, Zoom allows you ...",""],
["using_the_64_bit_indexer.htm","Using the 64-bit Indexer","Using the 64-bit Indexer The 64-bit Indexer is only available in the Enterprise Edition. You can find the 64-bit version of the Zoom Indexer under...",""],
["using_the_plugins.htm","Using the plugins","Using the plugins Once the plugin is installed, all you have to do is open the Configure dialog window, and add the file extension supported to th...",""],
["weightings.htm","Weightings","Weightings Word weighting These drop-downs allow you to increase or decrease the importance of words found, depending on whether it was found with...",""],
["whats_new.htm","What&#39;s New","What&#39;s New Version 7 brings Zoom to a new level of platform flexibility and usage possibilities for all web developers -- from enthusiast web site...",""],
["what_is_asp.htm","What is ASP (Classic ASP)?","What is ASP (aka Classic ASP)? ASP (Active Server Pages), also known as Classic ASP, is the Microsoft equivalent to PHP, and comes packaged with m...",""],
["what_is_aspdotnet.htm","What is ASP.NET?","What is ASP.NET? ASP.NET is a web application framework from Microsoft. It is NOT the same as ASP (which is also referred to as \"Classic ASP\") and...",""],
["what_is_cgi.htm","What is CGI?","What is CGI? CGI (Common Gateway Interface) is a method of running programs on a server over the web. This is different to PHP and ASP in that it ...",""],
["what_is_javascript.htm","What is Javascript?","What is Javascript? Javascript is a scripting language that allows a web page to tell the browser what to do. It is a client-side language, meanin...",""],
["what_is_php.htm","What is PHP?","What is PHP? PHP (PHP: Hypertext Preprocessor) is a software package installed on web servers to provide scripting capabilities. It is commonly fo...",""],
["what_is_php_asp_cgi_or_javascr.htm","What is PHP, ASP, CGI, or JavaScript?","What is PHP, ASP, ASP.NET, CGI, or JavaScript? This chapter serves to provide beginners with an explanation of some of the technologies and termin...",""],
["what_should_i_do_first.htm","What should I do first?","What should I do first? The following can serve as a guide for first-time users, or if you are not sure what you should do first. 1. Install the Z...",""],
["what_to_do_after_indexing.htm","What to do after indexing","What to do after indexing Once you have indexed your website, you will need to upload or copy the files created by the Indexer to your web-server ...",""],
["what_will_it_look_like.htm","What will the end result look like?","What will the end result look like? To give you an idea of what the resulting search page could look like, the following is a screenshot of a Zoom...",""],
["where_is_my_search_page.htm","Where is my search page?","Where is my search page? Once you have uploaded or copied the required files across to your server, you can open the following file in your browse...",""],
["where_is_the_program_data_dire.htm","Where is the Program Data directory?","Where is the Program Data directory? The Program Data directory is used to store files which are used by Zoom. This includes the plugins, source c...",""],
["which_search_script_platform.htm","Which search script platform should I use?","Which search script platform should I use? The search script is available in three different versions so that you can select what best suits your ...",""],
["word_delimitation_when_indexin.htm","Word delimitation when indexing","Word delimitation when indexing When building the index, the indexer must decide how to split a sentence up into words. Any characters in the foll...",""],
["word_delimitation_when_searchi.htm","Word delimitation when searching","Word delimitation when searching When a visitor on your search page enters a search query, the script must decide how to split a search phrase up ...",""],
["xmlrss_output.htm","XML/RSS output (CGI only)","XML/RSS output (CGI only) This option is only available for the CGI platform. Zoom can now return search results in an OpenSearch compatible XML/R...",""],
["zip_file_support.htm","ZIP file support","ZIP file support ZIP file support is built into the Indexer. This means that it is different to the other file extensions listed on the \" File for...",""],
["zoomimage.htm","Associating an image with a particular page","Associating an image with a particular page If you wish to associate a single image with a particular page, you can use the ZOOMIMAGE meta tag to ...",""],
["zoomwords.htm","Manually add words into the index","Manually add words into the index There is often the need to add words into the index that are not present in the text of the page itself. By doin...",""],
["zoom_search_engine_indexer.htm","Using the Zoom Search Engine Indexer","Using the Zoom Search Engine Indexer The Zoom Indexer is a Windows application that scans your entire website and indexes the content and informat...",""]];
